import './js/css';
import './js/pdf';
import './js/img';
import './js/ScrollScript';
import './js/DataCalcScript';
import './js/ArrowFucScript';
import './js/WhiteDarkModeScript';
// import './js/SideEventScript';
import './js/OpenProjectScript';
import './js/EmailCopyScript';
import './js/Mount2Skills';
import './js/Mount2Contact';
import './js/Mount2SideList';
